openapi: 3.0.3

info:
  title: Kitchen API
  description: API that allows to manage the production of orders in the Kitchen
  version: 1.0.0

servers:
  - url: http://127.0.0.1:5000
    description: URL for local development and testing
  - url: https://coffeemesh.com
    description: main production server
  - url: https://coffeemesh-staging.com
    description: staging server for testing purposes only 

paths:
  /kitchen/schedules:
    get:
      summary: Returns a list of orders scheduled for production
      tags:
        - kitchen
      parameters:
        - name: progress
          in: query
          description: >-
            Whether the order is in progress or not.
            In progress means it's in production in the kitchen.     
          required: false
          schema:
            type: boolean
        - name: limit
          in: query
          required: false
          schema:
            type: integer
        - name: since
          in: query
          required: false
          schema:
            type: string
            format: 'date-time'      
      responses:
        '200':
          description: A list of scheduled orders
          content:
            application/json:
              schema:
                additionalProperties: false
                type: object
                properties:
                  schedules:
                    $ref: '#components/schemas/GetScheduledOrderSchema'

  /kitchen/schedules/{schedule_id}:
  /kitchen/schedules/{schedule_id}/status:
  /kitchen/schedules/{schedule_id}/cancel:



components:
